dependencies {
    implementation project(':model')

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    // Si usas Lombok también (recomendado para que se hablen bien)
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'


    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'

    runtimeOnly 'de.flapdoodle.embed:de.flapdoodle.embed.mongo:4.21.0' // TODO: remove this dependency to connect to real database
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
}
