server:
  port: 8080

spring:
  application:
    name: "LogiFlowShipmentService" # Este nombre debe ser igual al del archivo .yaml en la carpeta

  config:
    import: "configserver:http://localhost:8888/" # El "cable" hacia el servidor

  devtools:
    add-properties: false